"""autogenerated by genpy from shm_led_mouth/LEDMatrixCmd.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import shm_led_mouth.msg
import std_msgs.msg

class LEDMatrixCmd(genpy.Message):
  _md5sum = "e6c5973b6a371aea4cb4dbb5179512f6"
  _type = "shm_led_mouth/LEDMatrixCmd"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
uint8 enable
LEDMatrixRow[] row

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: shm_led_mouth/LEDMatrixRow
LEDMatrixRGB[] column
================================================================================
MSG: shm_led_mouth/LEDMatrixRGB
uint32 r
uint32 g
uint32 b
"""
  __slots__ = ['header','enable','row']
  _slot_types = ['std_msgs/Header','uint8','shm_led_mouth/LEDMatrixRow[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,enable,row

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LEDMatrixCmd, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.enable is None:
        self.enable = 0
      if self.row is None:
        self.row = []
    else:
      self.header = std_msgs.msg.Header()
      self.enable = 0
      self.row = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.enable))
      length = len(self.row)
      buff.write(_struct_I.pack(length))
      for val1 in self.row:
        length = len(val1.column)
        buff.write(_struct_I.pack(length))
        for val2 in val1.column:
          _x = val2
          buff.write(_struct_3I.pack(_x.r, _x.g, _x.b))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.row is None:
        self.row = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.enable,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.row = []
      for i in range(0, length):
        val1 = shm_led_mouth.msg.LEDMatrixRow()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.column = []
        for i in range(0, length):
          val2 = shm_led_mouth.msg.LEDMatrixRGB()
          _x = val2
          start = end
          end += 12
          (_x.r, _x.g, _x.b,) = _struct_3I.unpack(str[start:end])
          val1.column.append(val2)
        self.row.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.enable))
      length = len(self.row)
      buff.write(_struct_I.pack(length))
      for val1 in self.row:
        length = len(val1.column)
        buff.write(_struct_I.pack(length))
        for val2 in val1.column:
          _x = val2
          buff.write(_struct_3I.pack(_x.r, _x.g, _x.b))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.row is None:
        self.row = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.enable,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.row = []
      for i in range(0, length):
        val1 = shm_led_mouth.msg.LEDMatrixRow()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.column = []
        for i in range(0, length):
          val2 = shm_led_mouth.msg.LEDMatrixRGB()
          _x = val2
          start = end
          end += 12
          (_x.r, _x.g, _x.b,) = _struct_3I.unpack(str[start:end])
          val1.column.append(val2)
        self.row.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_B = struct.Struct("<B")
