(cl:in-package m3_client-srv)
(cl:export '(CHAIN-VAL
          CHAIN
          BASE-VAL
          BASE
          JOINT_NAMES-VAL
          JOINT_NAMES
          TORQUE-VAL
          TORQUE
          TORQUEDOT-VAL
          TORQUEDOT
          THETA-VAL
          THETA
          THETADOT-VAL
          THETADOT
          THETADOTDOT-VAL
          THETADOTDOT
          COMPLETED_SPLINE_IDX-VAL
          COMPLETED_SPLINE_IDX
          END_POS-VAL
          END_POS
          END_ROT-VAL
          END_ROT
          J-VAL
          J
          G-VAL
          G
          END_TWIST-VAL
          END_TWIST
          PWM_CMD-VAL
          PWM_CMD
          MOTOR_ENABLED-VAL
          MOTOR_ENABLED
))