(cl:in-package m3meka_msgs-msg)
(cl:export '(BASE-VAL
          BASE
          MOTOR_TEMP-VAL
          MOTOR_TEMP
          AMP_TEMP-VAL
          AMP_TEMP
          CURRENT-VAL
          CURRENT
          TORQUE-VAL
          TORQUE
          TORQUEDOT-VAL
          TORQUEDOT
          THETA-VAL
          THETA
          THETADOT-VAL
          THETADOT
          THETADOTDOT-VAL
          THETADOTDOT
          TORQUE_GRAVITY-VAL
          TORQUE_GRAVITY
          PWM_CMD-VAL
          PWM_CMD
          AMBIENT_TEMP-VAL
          AMBIENT_TEMP
          CASE_TEMP-VAL
          CASE_TEMP
          POWER-VAL
          POWER
          FLAGS-VAL
          FLAGS
))