# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='hand_ua.proto',
  package='',
  serialized_pb='\n\rhand_ua.proto\x1a\x14\x63omponent_base.proto\"\x80\x01\n\x0eM3HandUAStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12\x13\n\x0btheta_thumb\x18\x02 \x03(\x01\x12\x13\n\x0btheta_index\x18\x03 \x03(\x01\x12\x12\n\ntheta_ring\x18\x04 \x03(\x01\x12\x13\n\x0btheta_pinky\x18\x05 \x03(\x01\"\x1f\n\x0fM3HandUACommand\x12\x0c\n\x04test\x18\x01 \x01(\x01\"z\n\rM3HandUAParam\x12\x19\n\x11\x66lex_factor_thumb\x18\x01 \x03(\x01\x12\x19\n\x11\x66lex_factor_index\x18\x02 \x03(\x01\x12\x18\n\x10\x66lex_factor_ring\x18\x03 \x03(\x01\x12\x19\n\x11\x66lex_factor_pinky\x18\x04 \x03(\x01\x42\x02H\x01')




_M3HANDUASTATUS = descriptor.Descriptor(
  name='M3HandUAStatus',
  full_name='M3HandUAStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3HandUAStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_thumb', full_name='M3HandUAStatus.theta_thumb', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_index', full_name='M3HandUAStatus.theta_index', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_ring', full_name='M3HandUAStatus.theta_ring', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_pinky', full_name='M3HandUAStatus.theta_pinky', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=168,
)


_M3HANDUACOMMAND = descriptor.Descriptor(
  name='M3HandUACommand',
  full_name='M3HandUACommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3HandUACommand.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=170,
  serialized_end=201,
)


_M3HANDUAPARAM = descriptor.Descriptor(
  name='M3HandUAParam',
  full_name='M3HandUAParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='flex_factor_thumb', full_name='M3HandUAParam.flex_factor_thumb', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flex_factor_index', full_name='M3HandUAParam.flex_factor_index', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flex_factor_ring', full_name='M3HandUAParam.flex_factor_ring', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flex_factor_pinky', full_name='M3HandUAParam.flex_factor_pinky', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=203,
  serialized_end=325,
)

_M3HANDUASTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['M3HandUAStatus'] = _M3HANDUASTATUS
DESCRIPTOR.message_types_by_name['M3HandUACommand'] = _M3HANDUACOMMAND
DESCRIPTOR.message_types_by_name['M3HandUAParam'] = _M3HANDUAPARAM

class M3HandUAStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HANDUASTATUS
  
  # @@protoc_insertion_point(class_scope:M3HandUAStatus)

class M3HandUACommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HANDUACOMMAND
  
  # @@protoc_insertion_point(class_scope:M3HandUACommand)

class M3HandUAParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HANDUAPARAM
  
  # @@protoc_insertion_point(class_scope:M3HandUAParam)

# @@protoc_insertion_point(module_scope)
