# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='haptic_demo.proto',
  package='',
  serialized_pb='\n\x11haptic_demo.proto\x1a\x14\x63omponent_base.proto\">\n\x12M3HapticDemoStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12\x0b\n\x03\x66oo\x18\x02 \x01(\x01\"\xd0\x01\n\x11M3HapticDemoParam\x12\x0e\n\x06max_fx\x18\x01 \x01(\x01\x12\x0e\n\x06max_fy\x18\x02 \x01(\x01\x12\x0e\n\x06max_fz\x18\x03 \x01(\x01\x12\x0b\n\x03x_k\x18\x04 \x01(\x01\x12\x0b\n\x03y_k\x18\x05 \x01(\x01\x12\x0b\n\x03z_k\x18\x06 \x01(\x01\x12\x11\n\tx_desired\x18\x07 \x01(\x01\x12\x11\n\ty_desired\x18\x08 \x01(\x01\x12\x11\n\tz_desired\x18\t \x01(\x01\x12\r\n\x05x_k_d\x18\n \x01(\x01\x12\r\n\x05y_k_d\x18\x0b \x01(\x01\x12\r\n\x05z_k_d\x18\x0c \x01(\x01\"%\n\x13M3HapticDemoCommand\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x42\x02H\x01')




_M3HAPTICDEMOSTATUS = descriptor.Descriptor(
  name='M3HapticDemoStatus',
  full_name='M3HapticDemoStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3HapticDemoStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='foo', full_name='M3HapticDemoStatus.foo', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=105,
)


_M3HAPTICDEMOPARAM = descriptor.Descriptor(
  name='M3HapticDemoParam',
  full_name='M3HapticDemoParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='max_fx', full_name='M3HapticDemoParam.max_fx', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_fy', full_name='M3HapticDemoParam.max_fy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_fz', full_name='M3HapticDemoParam.max_fz', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='x_k', full_name='M3HapticDemoParam.x_k', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y_k', full_name='M3HapticDemoParam.y_k', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z_k', full_name='M3HapticDemoParam.z_k', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='x_desired', full_name='M3HapticDemoParam.x_desired', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y_desired', full_name='M3HapticDemoParam.y_desired', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z_desired', full_name='M3HapticDemoParam.z_desired', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='x_k_d', full_name='M3HapticDemoParam.x_k_d', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y_k_d', full_name='M3HapticDemoParam.y_k_d', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z_k_d', full_name='M3HapticDemoParam.z_k_d', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=108,
  serialized_end=316,
)


_M3HAPTICDEMOCOMMAND = descriptor.Descriptor(
  name='M3HapticDemoCommand',
  full_name='M3HapticDemoCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='enable', full_name='M3HapticDemoCommand.enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=318,
  serialized_end=355,
)

_M3HAPTICDEMOSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['M3HapticDemoStatus'] = _M3HAPTICDEMOSTATUS
DESCRIPTOR.message_types_by_name['M3HapticDemoParam'] = _M3HAPTICDEMOPARAM
DESCRIPTOR.message_types_by_name['M3HapticDemoCommand'] = _M3HAPTICDEMOCOMMAND

class M3HapticDemoStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HAPTICDEMOSTATUS
  
  # @@protoc_insertion_point(class_scope:M3HapticDemoStatus)

class M3HapticDemoParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HAPTICDEMOPARAM
  
  # @@protoc_insertion_point(class_scope:M3HapticDemoParam)

class M3HapticDemoCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HAPTICDEMOCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3HapticDemoCommand)

# @@protoc_insertion_point(module_scope)
