# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='head_s2csp_ctrl.proto',
  package='',
  serialized_pb='\n\x15head_s2csp_ctrl.proto\x1a\x14\x63omponent_base.proto\"S\n\x15M3HeadS2CSPCtrlStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12\n\n\x02xe\x18\x02 \x03(\x01\x12\x11\n\ttheta_des\x18\x03 \x03(\x01\"N\n\x16M3HeadS2CSPCtrlCommand\x12\x0e\n\x06target\x18\x01 \x03(\x01\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x05\x12\x14\n\x0ctheta_des_j2\x18\x03 \x01(\x01\"q\n\x14M3HeadS2CSPCtrlParam\x12\x13\n\x0btarget_slew\x18\x01 \x01(\x01\x12\x10\n\x08slew_des\x18\x02 \x03(\x01\x12\x10\n\x08theta_db\x18\x03 \x03(\x01\x12\x10\n\x08ratio_j0\x18\x04 \x01(\x01\x12\x0e\n\x06origin\x18\x05 \x03(\x01\x42\x02H\x01')




_M3HEADS2CSPCTRLSTATUS = descriptor.Descriptor(
  name='M3HeadS2CSPCtrlStatus',
  full_name='M3HeadS2CSPCtrlStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3HeadS2CSPCtrlStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xe', full_name='M3HeadS2CSPCtrlStatus.xe', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_des', full_name='M3HeadS2CSPCtrlStatus.theta_des', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=130,
)


_M3HEADS2CSPCTRLCOMMAND = descriptor.Descriptor(
  name='M3HeadS2CSPCtrlCommand',
  full_name='M3HeadS2CSPCtrlCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='target', full_name='M3HeadS2CSPCtrlCommand.target', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enable', full_name='M3HeadS2CSPCtrlCommand.enable', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_des_j2', full_name='M3HeadS2CSPCtrlCommand.theta_des_j2', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=210,
)


_M3HEADS2CSPCTRLPARAM = descriptor.Descriptor(
  name='M3HeadS2CSPCtrlParam',
  full_name='M3HeadS2CSPCtrlParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='target_slew', full_name='M3HeadS2CSPCtrlParam.target_slew', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='slew_des', full_name='M3HeadS2CSPCtrlParam.slew_des', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_db', full_name='M3HeadS2CSPCtrlParam.theta_db', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ratio_j0', full_name='M3HeadS2CSPCtrlParam.ratio_j0', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='origin', full_name='M3HeadS2CSPCtrlParam.origin', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=325,
)

_M3HEADS2CSPCTRLSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['M3HeadS2CSPCtrlStatus'] = _M3HEADS2CSPCTRLSTATUS
DESCRIPTOR.message_types_by_name['M3HeadS2CSPCtrlCommand'] = _M3HEADS2CSPCTRLCOMMAND
DESCRIPTOR.message_types_by_name['M3HeadS2CSPCtrlParam'] = _M3HEADS2CSPCTRLPARAM

class M3HeadS2CSPCtrlStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HEADS2CSPCTRLSTATUS
  
  # @@protoc_insertion_point(class_scope:M3HeadS2CSPCtrlStatus)

class M3HeadS2CSPCtrlCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HEADS2CSPCTRLCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3HeadS2CSPCtrlCommand)

class M3HeadS2CSPCtrlParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HEADS2CSPCTRLPARAM
  
  # @@protoc_insertion_point(class_scope:M3HeadS2CSPCtrlParam)

# @@protoc_insertion_point(module_scope)
