# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='joint_array_mode.proto',
  package='',
  serialized_pb='\n\x16joint_array_mode.proto*\x89\x03\n\x10JOINT_ARRAY_MODE\x12\x18\n\x14JOINT_ARRAY_MODE_OFF\x10\x00\x12\x18\n\x14JOINT_ARRAY_MODE_PWM\x10\x01\x12\x1b\n\x17JOINT_ARRAY_MODE_TORQUE\x10\x02\x12\x1a\n\x16JOINT_ARRAY_MODE_THETA\x10\x03\x12\x1e\n\x1aJOINT_ARRAY_MODE_TORQUE_GC\x10\x04\x12\x1d\n\x19JOINT_ARRAY_MODE_THETA_GC\x10\x05\x12\x1d\n\x19JOINT_ARRAY_MODE_THETA_MJ\x10\x06\x12 \n\x1cJOINT_ARRAY_MODE_THETA_GC_MJ\x10\x07\x12!\n\x1dJOINT_ARRAY_MODE_SPLINED_TRAJ\x10\x08\x12$\n JOINT_ARRAY_MODE_SPLINED_TRAJ_GC\x10\t\x12\x1f\n\x1bJOINT_ARRAY_MODE_TORQUE_SHM\x10\n\x12\x1e\n\x1aJOINT_ARRAY_MODE_ANGLE_SHM\x10\x0b\x42\x02H\x01')

_JOINT_ARRAY_MODE = descriptor.EnumDescriptor(
  name='JOINT_ARRAY_MODE',
  full_name='JOINT_ARRAY_MODE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_OFF', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_PWM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_TORQUE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_TORQUE_GC', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA_GC', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA_MJ', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA_GC_MJ', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_SPLINED_TRAJ', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_SPLINED_TRAJ_GC', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_TORQUE_SHM', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_ANGLE_SHM', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=27,
  serialized_end=420,
)


JOINT_ARRAY_MODE_OFF = 0
JOINT_ARRAY_MODE_PWM = 1
JOINT_ARRAY_MODE_TORQUE = 2
JOINT_ARRAY_MODE_THETA = 3
JOINT_ARRAY_MODE_TORQUE_GC = 4
JOINT_ARRAY_MODE_THETA_GC = 5
JOINT_ARRAY_MODE_THETA_MJ = 6
JOINT_ARRAY_MODE_THETA_GC_MJ = 7
JOINT_ARRAY_MODE_SPLINED_TRAJ = 8
JOINT_ARRAY_MODE_SPLINED_TRAJ_GC = 9
JOINT_ARRAY_MODE_TORQUE_SHM = 10
JOINT_ARRAY_MODE_ANGLE_SHM = 11



# @@protoc_insertion_point(module_scope)
