# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='joint_zlift_shm.proto',
  package='',
  serialized_pb='\n\x15joint_zlift_shm.proto\x1a\x14\x63omponent_base.proto\"B\n\x15M3JointZLiftShmStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12\x0c\n\x04test\x18\x02 \x01(\x01\"&\n\x16M3JointZLiftShmCommand\x12\x0c\n\x04test\x18\x01 \x01(\x01\"$\n\x14M3JointZLiftShmParam\x12\x0c\n\x04test\x18\x01 \x01(\x01\x42\x02H\x01')




_M3JOINTZLIFTSHMSTATUS = descriptor.Descriptor(
  name='M3JointZLiftShmStatus',
  full_name='M3JointZLiftShmStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3JointZLiftShmStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test', full_name='M3JointZLiftShmStatus.test', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=113,
)


_M3JOINTZLIFTSHMCOMMAND = descriptor.Descriptor(
  name='M3JointZLiftShmCommand',
  full_name='M3JointZLiftShmCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3JointZLiftShmCommand.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=153,
)


_M3JOINTZLIFTSHMPARAM = descriptor.Descriptor(
  name='M3JointZLiftShmParam',
  full_name='M3JointZLiftShmParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3JointZLiftShmParam.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=155,
  serialized_end=191,
)

_M3JOINTZLIFTSHMSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['M3JointZLiftShmStatus'] = _M3JOINTZLIFTSHMSTATUS
DESCRIPTOR.message_types_by_name['M3JointZLiftShmCommand'] = _M3JOINTZLIFTSHMCOMMAND
DESCRIPTOR.message_types_by_name['M3JointZLiftShmParam'] = _M3JOINTZLIFTSHMPARAM

class M3JointZLiftShmStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTZLIFTSHMSTATUS
  
  # @@protoc_insertion_point(class_scope:M3JointZLiftShmStatus)

class M3JointZLiftShmCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTZLIFTSHMCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3JointZLiftShmCommand)

class M3JointZLiftShmParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTZLIFTSHMPARAM
  
  # @@protoc_insertion_point(class_scope:M3JointZLiftShmParam)

# @@protoc_insertion_point(module_scope)
