# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='led_matrix_ec_shm.proto',
  package='',
  serialized_pb='\n\x17led_matrix_ec_shm.proto\x1a\x14\x63omponent_base.proto\"C\n\x16M3LedMatrixEcShmStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12\x0c\n\x04test\x18\x02 \x01(\x01\"\'\n\x17M3LedMatrixEcShmCommand\x12\x0c\n\x04test\x18\x01 \x01(\x01\"%\n\x15M3LedMatrixEcShmParam\x12\x0c\n\x04test\x18\x01 \x01(\x01\x42\x02H\x01')




_M3LEDMATRIXECSHMSTATUS = descriptor.Descriptor(
  name='M3LedMatrixEcShmStatus',
  full_name='M3LedMatrixEcShmStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3LedMatrixEcShmStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test', full_name='M3LedMatrixEcShmStatus.test', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=116,
)


_M3LEDMATRIXECSHMCOMMAND = descriptor.Descriptor(
  name='M3LedMatrixEcShmCommand',
  full_name='M3LedMatrixEcShmCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3LedMatrixEcShmCommand.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=157,
)


_M3LEDMATRIXECSHMPARAM = descriptor.Descriptor(
  name='M3LedMatrixEcShmParam',
  full_name='M3LedMatrixEcShmParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3LedMatrixEcShmParam.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=159,
  serialized_end=196,
)

_M3LEDMATRIXECSHMSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['M3LedMatrixEcShmStatus'] = _M3LEDMATRIXECSHMSTATUS
DESCRIPTOR.message_types_by_name['M3LedMatrixEcShmCommand'] = _M3LEDMATRIXECSHMCOMMAND
DESCRIPTOR.message_types_by_name['M3LedMatrixEcShmParam'] = _M3LEDMATRIXECSHMPARAM

class M3LedMatrixEcShmStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECSHMSTATUS
  
  # @@protoc_insertion_point(class_scope:M3LedMatrixEcShmStatus)

class M3LedMatrixEcShmCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECSHMCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3LedMatrixEcShmCommand)

class M3LedMatrixEcShmParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECSHMPARAM
  
  # @@protoc_insertion_point(class_scope:M3LedMatrixEcShmParam)

# @@protoc_insertion_point(module_scope)
