# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='ledx2xn_ec.proto',
  package='',
  serialized_pb='\n\x10ledx2xn_ec.proto\x1a\x14\x63omponent_base.proto\"\xc3\x01\n\x11M3LedX2XNEcStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12#\n\x08\x65thercat\x18\x02 \x01(\x0b\x32\x11.M3EtherCATStatus\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x12\x11\n\tadc_ext_a\x18\x04 \x01(\x05\x12\x11\n\tadc_ext_b\x18\x05 \x01(\x05\x12\x11\n\tadc_ext_c\x18\x06 \x01(\x05\x12\x11\n\tadc_ext_d\x18\x07 \x01(\x05\x12\r\n\x05\x66lags\x18\x08 \x01(\x05\"1\n\x0eM3LedX2XNEcRGB\x12\t\n\x01r\x18\x01 \x03(\x05\x12\t\n\x01g\x18\x02 \x03(\x05\x12\t\n\x01\x62\x18\x03 \x03(\x05\"~\n\x12M3LedX2XNEcCommand\x12\x10\n\x08\x65nable_a\x18\x01 \x01(\x05\x12\x10\n\x08\x65nable_b\x18\x02 \x01(\x05\x12!\n\x08\x62ranch_a\x18\x03 \x01(\x0b\x32\x0f.M3LedX2XNEcRGB\x12!\n\x08\x62ranch_b\x18\x04 \x01(\x0b\x32\x0f.M3LedX2XNEcRGB\"\"\n\x10M3LedX2XNEcParam\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\x05\x42\x02H\x01')




_M3LEDX2XNECSTATUS = descriptor.Descriptor(
  name='M3LedX2XNEcStatus',
  full_name='M3LedX2XNEcStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3LedX2XNEcStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ethercat', full_name='M3LedX2XNEcStatus.ethercat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3LedX2XNEcStatus.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_a', full_name='M3LedX2XNEcStatus.adc_ext_a', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_b', full_name='M3LedX2XNEcStatus.adc_ext_b', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_c', full_name='M3LedX2XNEcStatus.adc_ext_c', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_d', full_name='M3LedX2XNEcStatus.adc_ext_d', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='M3LedX2XNEcStatus.flags', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=238,
)


_M3LEDX2XNECRGB = descriptor.Descriptor(
  name='M3LedX2XNEcRGB',
  full_name='M3LedX2XNEcRGB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='r', full_name='M3LedX2XNEcRGB.r', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='g', full_name='M3LedX2XNEcRGB.g', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='b', full_name='M3LedX2XNEcRGB.b', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=240,
  serialized_end=289,
)


_M3LEDX2XNECCOMMAND = descriptor.Descriptor(
  name='M3LedX2XNEcCommand',
  full_name='M3LedX2XNEcCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='enable_a', full_name='M3LedX2XNEcCommand.enable_a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enable_b', full_name='M3LedX2XNEcCommand.enable_b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='branch_a', full_name='M3LedX2XNEcCommand.branch_a', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='branch_b', full_name='M3LedX2XNEcCommand.branch_b', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=291,
  serialized_end=417,
)


_M3LEDX2XNECPARAM = descriptor.Descriptor(
  name='M3LedX2XNEcParam',
  full_name='M3LedX2XNEcParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='config', full_name='M3LedX2XNEcParam.config', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=419,
  serialized_end=453,
)

_M3LEDX2XNECSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3LEDX2XNECSTATUS.fields_by_name['ethercat'].message_type = component_base_pb2._M3ETHERCATSTATUS
_M3LEDX2XNECCOMMAND.fields_by_name['branch_a'].message_type = _M3LEDX2XNECRGB
_M3LEDX2XNECCOMMAND.fields_by_name['branch_b'].message_type = _M3LEDX2XNECRGB
DESCRIPTOR.message_types_by_name['M3LedX2XNEcStatus'] = _M3LEDX2XNECSTATUS
DESCRIPTOR.message_types_by_name['M3LedX2XNEcRGB'] = _M3LEDX2XNECRGB
DESCRIPTOR.message_types_by_name['M3LedX2XNEcCommand'] = _M3LEDX2XNECCOMMAND
DESCRIPTOR.message_types_by_name['M3LedX2XNEcParam'] = _M3LEDX2XNECPARAM

class M3LedX2XNEcStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDX2XNECSTATUS
  
  # @@protoc_insertion_point(class_scope:M3LedX2XNEcStatus)

class M3LedX2XNEcRGB(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDX2XNECRGB
  
  # @@protoc_insertion_point(class_scope:M3LedX2XNEcRGB)

class M3LedX2XNEcCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDX2XNECCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3LedX2XNEcCommand)

class M3LedX2XNEcParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDX2XNECPARAM
  
  # @@protoc_insertion_point(class_scope:M3LedX2XNEcParam)

# @@protoc_insertion_point(module_scope)
