# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='loadx6.proto',
  package='',
  serialized_pb='\n\x0cloadx6.proto\x1a\x14\x63omponent_base.proto\"\x89\x01\n\x0eM3LoadX6Status\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12\x0e\n\x06wrench\x18\x02 \x03(\x01\x12\x11\n\tadc_ext_0\x18\x03 \x01(\x01\x12\x11\n\tadc_ext_1\x18\x04 \x01(\x01\x12\x11\n\tadc_ext_2\x18\x05 \x01(\x01\x12\x11\n\tdig_ext_0\x18\x06 \x01(\x01\"\x11\n\x0fM3LoadX6Command\"\x0f\n\rM3LoadX6ParamB\x02H\x01')




_M3LOADX6STATUS = descriptor.Descriptor(
  name='M3LoadX6Status',
  full_name='M3LoadX6Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3LoadX6Status.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wrench', full_name='M3LoadX6Status.wrench', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_0', full_name='M3LoadX6Status.adc_ext_0', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_1', full_name='M3LoadX6Status.adc_ext_1', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_2', full_name='M3LoadX6Status.adc_ext_2', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dig_ext_0', full_name='M3LoadX6Status.dig_ext_0', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=176,
)


_M3LOADX6COMMAND = descriptor.Descriptor(
  name='M3LoadX6Command',
  full_name='M3LoadX6Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=178,
  serialized_end=195,
)


_M3LOADX6PARAM = descriptor.Descriptor(
  name='M3LoadX6Param',
  full_name='M3LoadX6Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=197,
  serialized_end=212,
)

_M3LOADX6STATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
DESCRIPTOR.message_types_by_name['M3LoadX6Status'] = _M3LOADX6STATUS
DESCRIPTOR.message_types_by_name['M3LoadX6Command'] = _M3LOADX6COMMAND
DESCRIPTOR.message_types_by_name['M3LoadX6Param'] = _M3LOADX6PARAM

class M3LoadX6Status(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX6STATUS
  
  # @@protoc_insertion_point(class_scope:M3LoadX6Status)

class M3LoadX6Command(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX6COMMAND
  
  # @@protoc_insertion_point(class_scope:M3LoadX6Command)

class M3LoadX6Param(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX6PARAM
  
  # @@protoc_insertion_point(class_scope:M3LoadX6Param)

# @@protoc_insertion_point(module_scope)
