# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='loadx1_ec.proto',
  package='',
  serialized_pb='\n\x0floadx1_ec.proto\x1a\x14\x63omponent_base.proto\"\x8a\x01\n\x10M3LoadX1EcStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12#\n\x08\x65thercat\x18\x02 \x01(\x0b\x32\x11.M3EtherCATStatus\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x12\n\nadc_torque\x18\x04 \x01(\x05\x12\r\n\x05\x66lags\x18\x05 \x01(\x05\"\"\n\x11M3LoadX1EcCommand\x12\r\n\x05\x64ummy\x18\x01 \x01(\x05\" \n\x0fM3LoadX1EcParam\x12\r\n\x05\x64ummy\x18\x01 \x01(\x05\x42\x02H\x01')




_M3LOADX1ECSTATUS = descriptor.Descriptor(
  name='M3LoadX1EcStatus',
  full_name='M3LoadX1EcStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3LoadX1EcStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ethercat', full_name='M3LoadX1EcStatus.ethercat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3LoadX1EcStatus.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_torque', full_name='M3LoadX1EcStatus.adc_torque', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='M3LoadX1EcStatus.flags', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=180,
)


_M3LOADX1ECCOMMAND = descriptor.Descriptor(
  name='M3LoadX1EcCommand',
  full_name='M3LoadX1EcCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dummy', full_name='M3LoadX1EcCommand.dummy', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=182,
  serialized_end=216,
)


_M3LOADX1ECPARAM = descriptor.Descriptor(
  name='M3LoadX1EcParam',
  full_name='M3LoadX1EcParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dummy', full_name='M3LoadX1EcParam.dummy', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=218,
  serialized_end=250,
)

_M3LOADX1ECSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3LOADX1ECSTATUS.fields_by_name['ethercat'].message_type = component_base_pb2._M3ETHERCATSTATUS
DESCRIPTOR.message_types_by_name['M3LoadX1EcStatus'] = _M3LOADX1ECSTATUS
DESCRIPTOR.message_types_by_name['M3LoadX1EcCommand'] = _M3LOADX1ECCOMMAND
DESCRIPTOR.message_types_by_name['M3LoadX1EcParam'] = _M3LOADX1ECPARAM

class M3LoadX1EcStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX1ECSTATUS
  
  # @@protoc_insertion_point(class_scope:M3LoadX1EcStatus)

class M3LoadX1EcCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX1ECCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3LoadX1EcCommand)

class M3LoadX1EcParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX1ECPARAM
  
  # @@protoc_insertion_point(class_scope:M3LoadX1EcParam)

# @@protoc_insertion_point(module_scope)
