# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='pwr_ec.proto',
  package='',
  serialized_pb='\n\x0cpwr_ec.proto\x1a\x14\x63omponent_base.proto\"\xd3\x01\n\rM3PwrEcStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12#\n\x08\x65thercat\x18\x02 \x01(\x0b\x32\x11.M3EtherCATStatus\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x12\x15\n\rmotor_enabled\x18\x04 \x01(\x08\x12\x17\n\x0f\x61\x64\x63_bus_voltage\x18\x05 \x01(\x05\x12\x1b\n\x13\x61\x64\x63_current_digital\x18\x06 \x01(\x05\x12\x11\n\tadc_ext_0\x18\x07 \x01(\x05\x12\r\n\x05\x66lags\x18\x08 \x01(\x05\"&\n\x0eM3PwrEcCommand\x12\x14\n\x0c\x65nable_motor\x18\x01 \x01(\x05\"\x1e\n\x0cM3PwrEcParam\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\x05\x42\x02H\x01')




_M3PWRECSTATUS = descriptor.Descriptor(
  name='M3PwrEcStatus',
  full_name='M3PwrEcStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3PwrEcStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ethercat', full_name='M3PwrEcStatus.ethercat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3PwrEcStatus.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='motor_enabled', full_name='M3PwrEcStatus.motor_enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_bus_voltage', full_name='M3PwrEcStatus.adc_bus_voltage', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_current_digital', full_name='M3PwrEcStatus.adc_current_digital', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adc_ext_0', full_name='M3PwrEcStatus.adc_ext_0', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='M3PwrEcStatus.flags', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=250,
)


_M3PWRECCOMMAND = descriptor.Descriptor(
  name='M3PwrEcCommand',
  full_name='M3PwrEcCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='enable_motor', full_name='M3PwrEcCommand.enable_motor', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=252,
  serialized_end=290,
)


_M3PWRECPARAM = descriptor.Descriptor(
  name='M3PwrEcParam',
  full_name='M3PwrEcParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='config', full_name='M3PwrEcParam.config', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=292,
  serialized_end=322,
)

_M3PWRECSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3PWRECSTATUS.fields_by_name['ethercat'].message_type = component_base_pb2._M3ETHERCATSTATUS
DESCRIPTOR.message_types_by_name['M3PwrEcStatus'] = _M3PWRECSTATUS
DESCRIPTOR.message_types_by_name['M3PwrEcCommand'] = _M3PWRECCOMMAND
DESCRIPTOR.message_types_by_name['M3PwrEcParam'] = _M3PWRECPARAM

class M3PwrEcStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3PWRECSTATUS
  
  # @@protoc_insertion_point(class_scope:M3PwrEcStatus)

class M3PwrEcCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3PWRECCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3PwrEcCommand)

class M3PwrEcParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3PWRECPARAM
  
  # @@protoc_insertion_point(class_scope:M3PwrEcParam)

# @@protoc_insertion_point(module_scope)
