# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import component_base_pb2
import joint_array_mode_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='torque_shm.proto',
  package='',
  serialized_pb='\n\x10torque_shm.proto\x1a\x14\x63omponent_base.proto\x1a\x16joint_array_mode.proto\"~\n\x15M3TorqueShmBaseStatus\x12\x0e\n\x06torque\x18\x01 \x03(\x01\x12\r\n\x05theta\x18\x02 \x03(\x01\x12\x10\n\x08thetadot\x18\x03 \x03(\x01\x12$\n\tctrl_mode\x18\x04 \x03(\x0e\x32\x11.JOINT_ARRAY_MODE\x12\x0e\n\x06loadx6\x18\x05 \x03(\x01\"\\\n\x16M3TorqueShmBaseCommand\x12\x12\n\ntq_desired\x18\x01 \x03(\x01\x12\x11\n\tq_desired\x18\x02 \x03(\x01\x12\x1b\n\x13slew_rate_q_desired\x18\x03 \x03(\x01\"\xfe\x01\n\x11M3TorqueShmStatus\x12\x1b\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\r.M3BaseStatus\x12)\n\tright_arm\x18\x02 \x01(\x0b\x32\x16.M3TorqueShmBaseStatus\x12(\n\x08left_arm\x18\x03 \x01(\x0b\x32\x16.M3TorqueShmBaseStatus\x12%\n\x05torso\x18\x04 \x01(\x0b\x32\x16.M3TorqueShmBaseStatus\x12$\n\x04head\x18\x05 \x01(\x0b\x32\x16.M3TorqueShmBaseStatus\x12*\n\nright_hand\x18\x06 \x01(\x0b\x32\x16.M3TorqueShmBaseStatus\"\xfa\x01\n\x12M3TorqueShmCommand\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12*\n\tright_arm\x18\x02 \x01(\x0b\x32\x17.M3TorqueShmBaseCommand\x12)\n\x08left_arm\x18\x03 \x01(\x0b\x32\x17.M3TorqueShmBaseCommand\x12&\n\x05torso\x18\x04 \x01(\x0b\x32\x17.M3TorqueShmBaseCommand\x12%\n\x04head\x18\x05 \x01(\x0b\x32\x17.M3TorqueShmBaseCommand\x12+\n\nright_hand\x18\x06 \x01(\x0b\x32\x17.M3TorqueShmBaseCommand\" \n\x10M3TorqueShmParam\x12\x0c\n\x04test\x18\x01 \x01(\x01\x42\x02H\x01')




_M3TORQUESHMBASESTATUS = descriptor.Descriptor(
  name='M3TorqueShmBaseStatus',
  full_name='M3TorqueShmBaseStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='torque', full_name='M3TorqueShmBaseStatus.torque', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta', full_name='M3TorqueShmBaseStatus.theta', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadot', full_name='M3TorqueShmBaseStatus.thetadot', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ctrl_mode', full_name='M3TorqueShmBaseStatus.ctrl_mode', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='loadx6', full_name='M3TorqueShmBaseStatus.loadx6', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=192,
)


_M3TORQUESHMBASECOMMAND = descriptor.Descriptor(
  name='M3TorqueShmBaseCommand',
  full_name='M3TorqueShmBaseCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tq_desired', full_name='M3TorqueShmBaseCommand.tq_desired', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_desired', full_name='M3TorqueShmBaseCommand.q_desired', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='slew_rate_q_desired', full_name='M3TorqueShmBaseCommand.slew_rate_q_desired', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=194,
  serialized_end=286,
)


_M3TORQUESHMSTATUS = descriptor.Descriptor(
  name='M3TorqueShmStatus',
  full_name='M3TorqueShmStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3TorqueShmStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_arm', full_name='M3TorqueShmStatus.right_arm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_arm', full_name='M3TorqueShmStatus.left_arm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torso', full_name='M3TorqueShmStatus.torso', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='M3TorqueShmStatus.head', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_hand', full_name='M3TorqueShmStatus.right_hand', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=289,
  serialized_end=543,
)


_M3TORQUESHMCOMMAND = descriptor.Descriptor(
  name='M3TorqueShmCommand',
  full_name='M3TorqueShmCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3TorqueShmCommand.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_arm', full_name='M3TorqueShmCommand.right_arm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_arm', full_name='M3TorqueShmCommand.left_arm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torso', full_name='M3TorqueShmCommand.torso', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='M3TorqueShmCommand.head', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_hand', full_name='M3TorqueShmCommand.right_hand', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=546,
  serialized_end=796,
)


_M3TORQUESHMPARAM = descriptor.Descriptor(
  name='M3TorqueShmParam',
  full_name='M3TorqueShmParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3TorqueShmParam.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=798,
  serialized_end=830,
)

_M3TORQUESHMBASESTATUS.fields_by_name['ctrl_mode'].enum_type = joint_array_mode_pb2._JOINT_ARRAY_MODE
_M3TORQUESHMSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['right_arm'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['left_arm'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['torso'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['head'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['right_hand'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMCOMMAND.fields_by_name['right_arm'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['left_arm'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['torso'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['head'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['right_hand'].message_type = _M3TORQUESHMBASECOMMAND
DESCRIPTOR.message_types_by_name['M3TorqueShmBaseStatus'] = _M3TORQUESHMBASESTATUS
DESCRIPTOR.message_types_by_name['M3TorqueShmBaseCommand'] = _M3TORQUESHMBASECOMMAND
DESCRIPTOR.message_types_by_name['M3TorqueShmStatus'] = _M3TORQUESHMSTATUS
DESCRIPTOR.message_types_by_name['M3TorqueShmCommand'] = _M3TORQUESHMCOMMAND
DESCRIPTOR.message_types_by_name['M3TorqueShmParam'] = _M3TORQUESHMPARAM

class M3TorqueShmBaseStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMBASESTATUS
  
  # @@protoc_insertion_point(class_scope:M3TorqueShmBaseStatus)

class M3TorqueShmBaseCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMBASECOMMAND
  
  # @@protoc_insertion_point(class_scope:M3TorqueShmBaseCommand)

class M3TorqueShmStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMSTATUS
  
  # @@protoc_insertion_point(class_scope:M3TorqueShmStatus)

class M3TorqueShmCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMCOMMAND
  
  # @@protoc_insertion_point(class_scope:M3TorqueShmCommand)

class M3TorqueShmParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMPARAM
  
  # @@protoc_insertion_point(class_scope:M3TorqueShmParam)

# @@protoc_insertion_point(module_scope)
