// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: joint_mode_ros.proto

#ifndef PROTOBUF_joint_5fmode_5fros_2eproto__INCLUDED
#define PROTOBUF_joint_5fmode_5fros_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_joint_5fmode_5fros_2eproto();
void protobuf_AssignDesc_joint_5fmode_5fros_2eproto();
void protobuf_ShutdownFile_joint_5fmode_5fros_2eproto();


enum JOINT_MODE_ROS {
  JOINT_MODE_ROS_OFF = 0,
  JOINT_MODE_ROS_THETA = 1,
  JOINT_MODE_ROS_THETA_GC = 2,
  JOINT_MODE_ROS_TORQUE_GC = 3
};
bool JOINT_MODE_ROS_IsValid(int value);
const JOINT_MODE_ROS JOINT_MODE_ROS_MIN = JOINT_MODE_ROS_OFF;
const JOINT_MODE_ROS JOINT_MODE_ROS_MAX = JOINT_MODE_ROS_TORQUE_GC;
const int JOINT_MODE_ROS_ARRAYSIZE = JOINT_MODE_ROS_MAX + 1;

const ::google::protobuf::EnumDescriptor* JOINT_MODE_ROS_descriptor();
inline const ::std::string& JOINT_MODE_ROS_Name(JOINT_MODE_ROS value) {
  return ::google::protobuf::internal::NameOfEnum(
    JOINT_MODE_ROS_descriptor(), value);
}
inline bool JOINT_MODE_ROS_Parse(
    const ::std::string& name, JOINT_MODE_ROS* value) {
  return ::google::protobuf::internal::ParseNamedEnum<JOINT_MODE_ROS>(
    JOINT_MODE_ROS_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< JOINT_MODE_ROS>() {
  return JOINT_MODE_ROS_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_joint_5fmode_5fros_2eproto__INCLUDED
