// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smoothing_mode.proto

#ifndef PROTOBUF_smoothing_5fmode_2eproto__INCLUDED
#define PROTOBUF_smoothing_5fmode_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_smoothing_5fmode_2eproto();
void protobuf_AssignDesc_smoothing_5fmode_2eproto();
void protobuf_ShutdownFile_smoothing_5fmode_2eproto();


enum SMOOTHING_MODE {
  SMOOTHING_MODE_OFF = 0,
  SMOOTHING_MODE_SLEW = 1,
  SMOOTHING_MODE_MIN_JERK = 2
};
bool SMOOTHING_MODE_IsValid(int value);
const SMOOTHING_MODE SMOOTHING_MODE_MIN = SMOOTHING_MODE_OFF;
const SMOOTHING_MODE SMOOTHING_MODE_MAX = SMOOTHING_MODE_MIN_JERK;
const int SMOOTHING_MODE_ARRAYSIZE = SMOOTHING_MODE_MAX + 1;

const ::google::protobuf::EnumDescriptor* SMOOTHING_MODE_descriptor();
inline const ::std::string& SMOOTHING_MODE_Name(SMOOTHING_MODE value) {
  return ::google::protobuf::internal::NameOfEnum(
    SMOOTHING_MODE_descriptor(), value);
}
inline bool SMOOTHING_MODE_Parse(
    const ::std::string& name, SMOOTHING_MODE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SMOOTHING_MODE>(
    SMOOTHING_MODE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< SMOOTHING_MODE>() {
  return SMOOTHING_MODE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_smoothing_5fmode_2eproto__INCLUDED
