; Auto-generated. Do not edit!


(in-package m3_client-srv)


;//! \htmlinclude M3JointArrayCmd-request.msg.html

(defclass <M3JointArrayCmd-request> (ros-message)
  ((tq_desired
    :reader tq_desired-val
    :initarg :tq_desired
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (pwm_desired
    :reader pwm_desired-val
    :initarg :pwm_desired
    :type (vector integer)
   :initform (make-array 0 :element-type 'integer :initial-element 0))
   (q_stiffness
    :reader q_stiffness-val
    :initarg :q_stiffness
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (ctrl_mode
    :reader ctrl_mode-val
    :initarg :ctrl_mode
    :type (vector integer)
   :initform (make-array 0 :element-type 'integer :initial-element 0))
   (q_desired
    :reader q_desired-val
    :initarg :q_desired
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (pos_desired
    :reader pos_desired-val
    :initarg :pos_desired
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (qdot_desired
    :reader qdot_desired-val
    :initarg :qdot_desired
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (q_slew_rate
    :reader q_slew_rate-val
    :initarg :q_slew_rate
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0)))
)
(defmethod serialize ((msg <M3JointArrayCmd-request>) ostream)
  "Serializes a message object of type '<M3JointArrayCmd-request>"
  (let ((__ros_arr_len (length (slot-value msg 'tq_desired))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'tq_desired))
  (let ((__ros_arr_len (length (slot-value msg 'pwm_desired))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele)   (write-byte (ldb (byte 8 0) ele) ostream)
  (write-byte (ldb (byte 8 8) ele) ostream)
  (write-byte (ldb (byte 8 16) ele) ostream)
  (write-byte (ldb (byte 8 24) ele) ostream))
    (slot-value msg 'pwm_desired))
  (let ((__ros_arr_len (length (slot-value msg 'q_stiffness))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'q_stiffness))
  (let ((__ros_arr_len (length (slot-value msg 'ctrl_mode))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele)   (write-byte (ldb (byte 8 0) ele) ostream)
  (write-byte (ldb (byte 8 8) ele) ostream)
  (write-byte (ldb (byte 8 16) ele) ostream)
  (write-byte (ldb (byte 8 24) ele) ostream))
    (slot-value msg 'ctrl_mode))
  (let ((__ros_arr_len (length (slot-value msg 'q_desired))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'q_desired))
  (let ((__ros_arr_len (length (slot-value msg 'pos_desired))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'pos_desired))
  (let ((__ros_arr_len (length (slot-value msg 'qdot_desired))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'qdot_desired))
  (let ((__ros_arr_len (length (slot-value msg 'q_slew_rate))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'q_slew_rate))
)
(defmethod deserialize ((msg <M3JointArrayCmd-request>) istream)
  "Deserializes a message object of type '<M3JointArrayCmd-request>"
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'tq_desired) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'tq_desired)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'pwm_desired) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'pwm_desired)))
      (dotimes (i __ros_arr_len)
(setf (ldb (byte 8 0) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 8) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 16) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 24) (aref vals i)) (read-byte istream)))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'q_stiffness) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'q_stiffness)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'ctrl_mode) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'ctrl_mode)))
      (dotimes (i __ros_arr_len)
(setf (ldb (byte 8 0) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 8) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 16) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 24) (aref vals i)) (read-byte istream)))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'q_desired) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'q_desired)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'pos_desired) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'pos_desired)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'qdot_desired) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'qdot_desired)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'q_slew_rate) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'q_slew_rate)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(defmethod ros-datatype ((msg (eql '<M3JointArrayCmd-request>)))
  "Returns string type for a service object of type '<M3JointArrayCmd-request>"
  "m3_client/M3JointArrayCmdRequest")
(defmethod md5sum ((type (eql '<M3JointArrayCmd-request>)))
  "Returns md5sum for a message object of type '<M3JointArrayCmd-request>"
  "4432a41b7a22c858d4c20d1bddbf0718")
(defmethod message-definition ((type (eql '<M3JointArrayCmd-request>)))
  "Returns full string definition for message of type '<M3JointArrayCmd-request>"
  (format nil "float32[] tq_desired		#Desired torque (mNm)~%int32[] pwm_desired		#Desired pwm (ticks)~%float32[] q_stiffness		#Desired joint stifness (0.0-1.0, scalar)~%int32[] ctrl_mode		#Desired arm control mode ~%float32[] q_desired		#Desired joint angle (Rad)~%float32[] pos_desired		#Desired end pos (x,y,z,yaw,pitch,roll) (mm,rad)~%float32[] qdot_desired		#Desired joint angle (Deg)~%float32[] q_slew_rate		#Slew Rates (max ang velocity) for joints (Deg/sec)~%~%"))
(defmethod serialization-length ((msg <M3JointArrayCmd-request>))
  (+ 0
     4 (reduce #'+ (slot-value msg 'tq_desired) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'pwm_desired) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'q_stiffness) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'ctrl_mode) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'q_desired) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'pos_desired) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'qdot_desired) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'q_slew_rate) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
))
(defmethod ros-message-to-list ((msg <M3JointArrayCmd-request>))
  "Converts a ROS message object to a list"
  (list '<M3JointArrayCmd-request>
    (cons ':tq_desired (tq_desired-val msg))
    (cons ':pwm_desired (pwm_desired-val msg))
    (cons ':q_stiffness (q_stiffness-val msg))
    (cons ':ctrl_mode (ctrl_mode-val msg))
    (cons ':q_desired (q_desired-val msg))
    (cons ':pos_desired (pos_desired-val msg))
    (cons ':qdot_desired (qdot_desired-val msg))
    (cons ':q_slew_rate (q_slew_rate-val msg))
))
;//! \htmlinclude M3JointArrayCmd-response.msg.html

(defclass <M3JointArrayCmd-response> (ros-message)
  ((response
    :reader response-val
    :initarg :response
    :type integer
    :initform 0))
)
(defmethod serialize ((msg <M3JointArrayCmd-response>) ostream)
  "Serializes a message object of type '<M3JointArrayCmd-response>"
    (write-byte (ldb (byte 8 0) (slot-value msg 'response)) ostream)
  (write-byte (ldb (byte 8 8) (slot-value msg 'response)) ostream)
  (write-byte (ldb (byte 8 16) (slot-value msg 'response)) ostream)
  (write-byte (ldb (byte 8 24) (slot-value msg 'response)) ostream)
)
(defmethod deserialize ((msg <M3JointArrayCmd-response>) istream)
  "Deserializes a message object of type '<M3JointArrayCmd-response>"
  (setf (ldb (byte 8 0) (slot-value msg 'response)) (read-byte istream))
  (setf (ldb (byte 8 8) (slot-value msg 'response)) (read-byte istream))
  (setf (ldb (byte 8 16) (slot-value msg 'response)) (read-byte istream))
  (setf (ldb (byte 8 24) (slot-value msg 'response)) (read-byte istream))
  msg
)
(defmethod ros-datatype ((msg (eql '<M3JointArrayCmd-response>)))
  "Returns string type for a service object of type '<M3JointArrayCmd-response>"
  "m3_client/M3JointArrayCmdResponse")
(defmethod md5sum ((type (eql '<M3JointArrayCmd-response>)))
  "Returns md5sum for a message object of type '<M3JointArrayCmd-response>"
  "4432a41b7a22c858d4c20d1bddbf0718")
(defmethod message-definition ((type (eql '<M3JointArrayCmd-response>)))
  "Returns full string definition for message of type '<M3JointArrayCmd-response>"
  (format nil "int32 response~%~%#repeated M3JointVia			vias=5;	 				//Joint trajectory vias~%~%"))
(defmethod serialization-length ((msg <M3JointArrayCmd-response>))
  (+ 0
     4
))
(defmethod ros-message-to-list ((msg <M3JointArrayCmd-response>))
  "Converts a ROS message object to a list"
  (list '<M3JointArrayCmd-response>
    (cons ':response (response-val msg))
))
(defmethod service-request-type ((msg (eql 'M3JointArrayCmd)))
  '<M3JointArrayCmd-request>)
(defmethod service-response-type ((msg (eql 'M3JointArrayCmd)))
  '<M3JointArrayCmd-response>)
(defmethod ros-datatype ((msg (eql 'M3JointArrayCmd)))
  "Returns string type for a service object of type '<M3JointArrayCmd>"
  "m3_client/M3JointArrayCmd")
