; Auto-generated. Do not edit!


(in-package m3_client-srv)


;//! \htmlinclude M3JointArrayStatus-request.msg.html

(defclass <M3JointArrayStatus-request> (ros-message)
  ((request
    :reader request-val
    :initarg :request
    :type integer
    :initform 0))
)
(defmethod serialize ((msg <M3JointArrayStatus-request>) ostream)
  "Serializes a message object of type '<M3JointArrayStatus-request>"
    (write-byte (ldb (byte 8 0) (slot-value msg 'request)) ostream)
  (write-byte (ldb (byte 8 8) (slot-value msg 'request)) ostream)
  (write-byte (ldb (byte 8 16) (slot-value msg 'request)) ostream)
  (write-byte (ldb (byte 8 24) (slot-value msg 'request)) ostream)
)
(defmethod deserialize ((msg <M3JointArrayStatus-request>) istream)
  "Deserializes a message object of type '<M3JointArrayStatus-request>"
  (setf (ldb (byte 8 0) (slot-value msg 'request)) (read-byte istream))
  (setf (ldb (byte 8 8) (slot-value msg 'request)) (read-byte istream))
  (setf (ldb (byte 8 16) (slot-value msg 'request)) (read-byte istream))
  (setf (ldb (byte 8 24) (slot-value msg 'request)) (read-byte istream))
  msg
)
(defmethod ros-datatype ((msg (eql '<M3JointArrayStatus-request>)))
  "Returns string type for a service object of type '<M3JointArrayStatus-request>"
  "m3_client/M3JointArrayStatusRequest")
(defmethod md5sum ((type (eql '<M3JointArrayStatus-request>)))
  "Returns md5sum for a message object of type '<M3JointArrayStatus-request>"
  "fd0ff7bf51cf3c5324e0ee2aef6015d7")
(defmethod message-definition ((type (eql '<M3JointArrayStatus-request>)))
  "Returns full string definition for message of type '<M3JointArrayStatus-request>"
  (format nil "int32 request~%~%"))
(defmethod serialization-length ((msg <M3JointArrayStatus-request>))
  (+ 0
     4
))
(defmethod ros-message-to-list ((msg <M3JointArrayStatus-request>))
  "Converts a ROS message object to a list"
  (list '<M3JointArrayStatus-request>
    (cons ':request (request-val msg))
))
;//! \htmlinclude M3JointArrayStatus-response.msg.html

(defclass <M3JointArrayStatus-response> (ros-message)
  ((base
    :reader base-val
    :initarg :base
    :type m3_client-msg:<M3BaseStatus>
    :initform (make-instance 'm3_client-msg:<M3BaseStatus>))
   (motor_temp
    :reader motor_temp-val
    :initarg :motor_temp
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (amp_temp
    :reader amp_temp-val
    :initarg :amp_temp
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (current
    :reader current-val
    :initarg :current
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (torque
    :reader torque-val
    :initarg :torque
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (torquedot
    :reader torquedot-val
    :initarg :torquedot
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (theta
    :reader theta-val
    :initarg :theta
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (thetadot
    :reader thetadot-val
    :initarg :thetadot
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (thetadotdot
    :reader thetadotdot-val
    :initarg :thetadotdot
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (completed_spline_idx
    :reader completed_spline_idx-val
    :initarg :completed_spline_idx
    :type integer
    :initform 0)
   (pwm_cmd
    :reader pwm_cmd-val
    :initarg :pwm_cmd
    :type (vector integer)
   :initform (make-array 0 :element-type 'integer :initial-element 0)))
)
(defmethod serialize ((msg <M3JointArrayStatus-response>) ostream)
  "Serializes a message object of type '<M3JointArrayStatus-response>"
  (serialize (slot-value msg 'base) ostream)
  (let ((__ros_arr_len (length (slot-value msg 'motor_temp))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'motor_temp))
  (let ((__ros_arr_len (length (slot-value msg 'amp_temp))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'amp_temp))
  (let ((__ros_arr_len (length (slot-value msg 'current))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'current))
  (let ((__ros_arr_len (length (slot-value msg 'torque))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'torque))
  (let ((__ros_arr_len (length (slot-value msg 'torquedot))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'torquedot))
  (let ((__ros_arr_len (length (slot-value msg 'theta))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'theta))
  (let ((__ros_arr_len (length (slot-value msg 'thetadot))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'thetadot))
  (let ((__ros_arr_len (length (slot-value msg 'thetadotdot))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)))
    (slot-value msg 'thetadotdot))
    (write-byte (ldb (byte 8 0) (slot-value msg 'completed_spline_idx)) ostream)
  (write-byte (ldb (byte 8 8) (slot-value msg 'completed_spline_idx)) ostream)
  (write-byte (ldb (byte 8 16) (slot-value msg 'completed_spline_idx)) ostream)
  (write-byte (ldb (byte 8 24) (slot-value msg 'completed_spline_idx)) ostream)
  (let ((__ros_arr_len (length (slot-value msg 'pwm_cmd))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele)   (write-byte (ldb (byte 8 0) ele) ostream)
  (write-byte (ldb (byte 8 8) ele) ostream)
  (write-byte (ldb (byte 8 16) ele) ostream)
  (write-byte (ldb (byte 8 24) ele) ostream))
    (slot-value msg 'pwm_cmd))
)
(defmethod deserialize ((msg <M3JointArrayStatus-response>) istream)
  "Deserializes a message object of type '<M3JointArrayStatus-response>"
  (deserialize (slot-value msg 'base) istream)
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'motor_temp) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'motor_temp)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'amp_temp) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'amp_temp)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'current) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'current)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'torque) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'torque)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'torquedot) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'torquedot)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'theta) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'theta)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'thetadot) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'thetadot)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'thetadotdot) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'thetadotdot)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (setf (ldb (byte 8 0) (slot-value msg 'completed_spline_idx)) (read-byte istream))
  (setf (ldb (byte 8 8) (slot-value msg 'completed_spline_idx)) (read-byte istream))
  (setf (ldb (byte 8 16) (slot-value msg 'completed_spline_idx)) (read-byte istream))
  (setf (ldb (byte 8 24) (slot-value msg 'completed_spline_idx)) (read-byte istream))
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'pwm_cmd) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'pwm_cmd)))
      (dotimes (i __ros_arr_len)
(setf (ldb (byte 8 0) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 8) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 16) (aref vals i)) (read-byte istream))
  (setf (ldb (byte 8 24) (aref vals i)) (read-byte istream)))))
  msg
)
(defmethod ros-datatype ((msg (eql '<M3JointArrayStatus-response>)))
  "Returns string type for a service object of type '<M3JointArrayStatus-response>"
  "m3_client/M3JointArrayStatusResponse")
(defmethod md5sum ((type (eql '<M3JointArrayStatus-response>)))
  "Returns md5sum for a message object of type '<M3JointArrayStatus-response>"
  "fd0ff7bf51cf3c5324e0ee2aef6015d7")
(defmethod message-definition ((type (eql '<M3JointArrayStatus-response>)))
  "Returns full string definition for message of type '<M3JointArrayStatus-response>"
  (format nil "M3BaseStatus base~%float32[] motor_temp	#(F)~%float32[] amp_temp	#(F)~%float32[] current	#(mA)~%float32[] torque	#(mNm)~%float32[] torquedot	#(mNm)~%float32[] theta		#(Rad)~%float32[] thetadot	#(Rad/s)~%float32[] thetadotdot	#(Rad/s^2)~%int32 completed_spline_idx	#Last spline command completed~%int32[] pwm_cmd		#Current PWM command to motor~%================================================================================~%MSG: m3_client/M3BaseStatus~%string name~%uint8 state~%int64 timestamp~%string rate~%string version~%~%~%~%"))
(defmethod serialization-length ((msg <M3JointArrayStatus-response>))
  (+ 0
     (serialization-length (slot-value msg 'base))
     4 (reduce #'+ (slot-value msg 'motor_temp) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'amp_temp) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'current) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'torque) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'torquedot) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'theta) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'thetadot) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4 (reduce #'+ (slot-value msg 'thetadotdot) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
     4
     4 (reduce #'+ (slot-value msg 'pwm_cmd) :key #'(lambda (ele) (declare (ignorable ele)) (+ 4)))
))
(defmethod ros-message-to-list ((msg <M3JointArrayStatus-response>))
  "Converts a ROS message object to a list"
  (list '<M3JointArrayStatus-response>
    (cons ':base (base-val msg))
    (cons ':motor_temp (motor_temp-val msg))
    (cons ':amp_temp (amp_temp-val msg))
    (cons ':current (current-val msg))
    (cons ':torque (torque-val msg))
    (cons ':torquedot (torquedot-val msg))
    (cons ':theta (theta-val msg))
    (cons ':thetadot (thetadot-val msg))
    (cons ':thetadotdot (thetadotdot-val msg))
    (cons ':completed_spline_idx (completed_spline_idx-val msg))
    (cons ':pwm_cmd (pwm_cmd-val msg))
))
(defmethod service-request-type ((msg (eql 'M3JointArrayStatus)))
  '<M3JointArrayStatus-request>)
(defmethod service-response-type ((msg (eql 'M3JointArrayStatus)))
  '<M3JointArrayStatus-response>)
(defmethod ros-datatype ((msg (eql 'M3JointArrayStatus)))
  "Returns string type for a service object of type '<M3JointArrayStatus>"
  "m3_client/M3JointArrayStatus")
