#!/bin/sh

MODULES=/usr/realtime-2.6.32.11-rtai-3.8.1/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi

rmmod=/sbin/rmmod

sync
$SUDO $rmmod m3ec.ko
#sync paranoia might be useful
sync
$SUDO $rmmod rtai_shm
sync
$SUDO $rmmod rtai_sem
if [ -f $MODULES/rtai_smi.ko ]
then
  sync
  $SUDO $rmmod rtai_smi
fi
sync
$SUDO $rmmod rtai_lxrt
#$rmmod rtai_smp
sync
$SUDO $rmmod rtai_hal
sync





