#!/bin/sh

export LD_LIBRARY_PATH=/usr/local/lib:/opt/ros/cturtle/ros/3rdparty/xmlrpcpp/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ros/cturtle/ros/core/roscpp/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ros/cturtle/ros/core/roslib/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ros/cturtle/ros/core/rosconsole/lib
source /opt/ros/cturtle/setup.sh

export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/mekabot/meka-ros-pkg:~/mekabot/m3core/ros:~/mekabot/m3meka/ros

#/usr/local/bin/m3rt_insmods
#/usr/local/bin/m3rt_rotate_logs






